on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Cehckout
      uses: actions/checkout@v2
    - name: Hello world action step
      uses: ./
      id: hello
      with:
        who-to-greet: 'Namra'
    - name: Get output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
